# Use an official Alpine Linux base (small footprint)
From alpine:latest

# Set a default environment variable
ENV GREETING="Hello, I am Boubacar and I will try to show you how to start with Docker!"

# Define the command to run when the container starts
CMD ["sh", "-c", "echo \"$GREETING\""]